name: "UI deploy MainNet"
on:
  release:
    types: [released]

jobs:
  deploy-mainnet:
    name: Deploy to MainNet site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MAINNET_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MAINNET_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.MAINNET_AWS_REGION }}
    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors public/ ${{ secrets.MAINNET_S3_BUCKET }}
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.MAINNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
